### ISSUE TITLE
Cannot find module js-yaml in web log

### ISSUE THREAD

**Issue by jamesalexw** [danslimmon/oscar#18]
Full error -

debugger listening on port 5858

module.js:340
    throw err;
          ^
Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/oscar/web/lib/conf.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by CloCkWeRX** [comment]
Fixed on master
