### ISSUE TITLE
HTTP Error 500: Internal Server Error crashes oscar

### ISSUE THREAD

**Issue by CloCkWeRX** [danslimmon/oscar#32]
```
Scanned barcode '9339423004229'
Traceback (most recent call last):
  File "/var/oscar/scan.py", line 210, in <module>
    desc = u.get_description(barcode)
  File "/var/oscar/scan.py", line 59, in get_description
    json_blob = urllib2.urlopen(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by CloCkWeRX** [comment]
http://www.digit-eyes.com/upcCode/9339423004229.html?l=en

**Comment by CloCkWeRX** [comment]
Wonder if this is #44
